# Generated by Django 4.2.21 on 2025-05-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astanahubparticipant',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
