# Generated by Django 4.2.21 on 2025-05-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_completed_alter_tasks_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='astanahubparticipant',
            options={'ordering': ['id'], 'verbose_name_plural': 'Участники Астана ХАБ'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['id'], 'verbose_name_plural': 'Ваши задачи'},
        ),
        migrations.AlterField(
            model_name='astanahubparticipant',
            name='company_bin',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='БИН организации'),
        ),
        migrations.AlterField(
            model_name='astanahubparticipant',
            name='company_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='astanahubparticipant',
            name='registration_data',
            field=models.DateField(blank=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='astanahubparticipant',
            name='status',
            field=models.CharField(max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='astanahubparticipant',
            name='valid_to',
            field=models.DateField(blank=True, verbose_name='Дата окончания регистрации'),
        ),
    ]
